version: "3.8"

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "5006:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./qr_output:/app/qr_output
    environment:
      - PORT=5001
      - UPLOAD_FOLDER=/app/uploads
      - OUTPUT_BASE=/app/qr_output
    restart: unless-stopped
